DELETE http://localhost:3001/api/blogs/631e033fd0f76c97ddec1c56
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzMWRmNGUwMDA4OGMyYmQ4NDFjZmEyZSIsImlhdCI6MTY2MjkxMTI4NiwiZXhwIjoxNjYyOTE0ODg2fQ.Qw_8Kou9ZQLpDpUAnaUZVXWnWWZt5tEpAGnltudRM